'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive1CheckBox() As Boolean
            Get
                Return CType(Me("Drive1CheckBox"),Boolean)
            End Get
            Set
                Me("Drive1CheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive2CheckBox() As Boolean
            Get
                Return CType(Me("Drive2CheckBox"),Boolean)
            End Get
            Set
                Me("Drive2CheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive3CheckBox() As Boolean
            Get
                Return CType(Me("Drive3CheckBox"),Boolean)
            End Get
            Set
                Me("Drive3CheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive4CheckBox() As Boolean
            Get
                Return CType(Me("Drive4CheckBox"),Boolean)
            End Get
            Set
                Me("Drive4CheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive5CheckBox() As Boolean
            Get
                Return CType(Me("Drive5CheckBox"),Boolean)
            End Get
            Set
                Me("Drive5CheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive1Dest() As String
            Get
                Return CType(Me("Drive1Dest"),String)
            End Get
            Set
                Me("Drive1Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive2Dest() As String
            Get
                Return CType(Me("Drive2Dest"),String)
            End Get
            Set
                Me("Drive2Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive3Dest() As String
            Get
                Return CType(Me("Drive3Dest"),String)
            End Get
            Set
                Me("Drive3Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive4Dest() As String
            Get
                Return CType(Me("Drive4Dest"),String)
            End Get
            Set
                Me("Drive4Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive5Dest() As String
            Get
                Return CType(Me("Drive5Dest"),String)
            End Get
            Set
                Me("Drive5Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive1Del() As Boolean
            Get
                Return CType(Me("Drive1Del"),Boolean)
            End Get
            Set
                Me("Drive1Del") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive2Del() As Boolean
            Get
                Return CType(Me("Drive2Del"),Boolean)
            End Get
            Set
                Me("Drive2Del") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive3Del() As Boolean
            Get
                Return CType(Me("Drive3Del"),Boolean)
            End Get
            Set
                Me("Drive3Del") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive4Del() As Boolean
            Get
                Return CType(Me("Drive4Del"),Boolean)
            End Get
            Set
                Me("Drive4Del") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive5Del() As Boolean
            Get
                Return CType(Me("Drive5Del"),Boolean)
            End Get
            Set
                Me("Drive5Del") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive1DelFolder() As String
            Get
                Return CType(Me("Drive1DelFolder"),String)
            End Get
            Set
                Me("Drive1DelFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive2DelFolder() As String
            Get
                Return CType(Me("Drive2DelFolder"),String)
            End Get
            Set
                Me("Drive2DelFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive3DelFolder() As String
            Get
                Return CType(Me("Drive3DelFolder"),String)
            End Get
            Set
                Me("Drive3DelFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive4DelFolder() As String
            Get
                Return CType(Me("Drive4DelFolder"),String)
            End Get
            Set
                Me("Drive4DelFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive5DelFolder() As String
            Get
                Return CType(Me("Drive5DelFolder"),String)
            End Get
            Set
                Me("Drive5DelFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PlotSourceFolder() As String
            Get
                Return CType(Me("PlotSourceFolder"),String)
            End Get
            Set
                Me("PlotSourceFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive1NickName() As String
            Get
                Return CType(Me("Drive1NickName"),String)
            End Get
            Set
                Me("Drive1NickName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive2NickName() As String
            Get
                Return CType(Me("Drive2NickName"),String)
            End Get
            Set
                Me("Drive2NickName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive3NickName() As String
            Get
                Return CType(Me("Drive3NickName"),String)
            End Get
            Set
                Me("Drive3NickName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive4NickName() As String
            Get
                Return CType(Me("Drive4NickName"),String)
            End Get
            Set
                Me("Drive4NickName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive5NickName() As String
            Get
                Return CType(Me("Drive5NickName"),String)
            End Get
            Set
                Me("Drive5NickName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property MaxConsecMoves() As Decimal
            Get
                Return CType(Me("MaxConsecMoves"),Decimal)
            End Get
            Set
                Me("MaxConsecMoves") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReservedSpace1() As Decimal
            Get
                Return CType(Me("ReservedSpace1"),Decimal)
            End Get
            Set
                Me("ReservedSpace1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReservedSpace2() As Decimal
            Get
                Return CType(Me("ReservedSpace2"),Decimal)
            End Get
            Set
                Me("ReservedSpace2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReservedSpace3() As Decimal
            Get
                Return CType(Me("ReservedSpace3"),Decimal)
            End Get
            Set
                Me("ReservedSpace3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReservedSpace4() As Decimal
            Get
                Return CType(Me("ReservedSpace4"),Decimal)
            End Get
            Set
                Me("ReservedSpace4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReservedSpace5() As Decimal
            Get
                Return CType(Me("ReservedSpace5"),Decimal)
            End Get
            Set
                Me("ReservedSpace5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive6CheckBox() As Boolean
            Get
                Return CType(Me("Drive6CheckBox"),Boolean)
            End Get
            Set
                Me("Drive6CheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive7CheckBox() As Boolean
            Get
                Return CType(Me("Drive7CheckBox"),Boolean)
            End Get
            Set
                Me("Drive7CheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive8CheckBox() As Boolean
            Get
                Return CType(Me("Drive8CheckBox"),Boolean)
            End Get
            Set
                Me("Drive8CheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive9CheckBox() As Boolean
            Get
                Return CType(Me("Drive9CheckBox"),Boolean)
            End Get
            Set
                Me("Drive9CheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive10CheckBox() As Boolean
            Get
                Return CType(Me("Drive10CheckBox"),Boolean)
            End Get
            Set
                Me("Drive10CheckBox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive6Dest() As String
            Get
                Return CType(Me("Drive6Dest"),String)
            End Get
            Set
                Me("Drive6Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive7Dest() As String
            Get
                Return CType(Me("Drive7Dest"),String)
            End Get
            Set
                Me("Drive7Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive8Dest() As String
            Get
                Return CType(Me("Drive8Dest"),String)
            End Get
            Set
                Me("Drive8Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive9Dest() As String
            Get
                Return CType(Me("Drive9Dest"),String)
            End Get
            Set
                Me("Drive9Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive10Dest() As String
            Get
                Return CType(Me("Drive10Dest"),String)
            End Get
            Set
                Me("Drive10Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive6Del() As Boolean
            Get
                Return CType(Me("Drive6Del"),Boolean)
            End Get
            Set
                Me("Drive6Del") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive7Del() As Boolean
            Get
                Return CType(Me("Drive7Del"),Boolean)
            End Get
            Set
                Me("Drive7Del") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive8Del() As Boolean
            Get
                Return CType(Me("Drive8Del"),Boolean)
            End Get
            Set
                Me("Drive8Del") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive9Del() As Boolean
            Get
                Return CType(Me("Drive9Del"),Boolean)
            End Get
            Set
                Me("Drive9Del") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Drive10Del() As Boolean
            Get
                Return CType(Me("Drive10Del"),Boolean)
            End Get
            Set
                Me("Drive10Del") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive6DelFolder() As String
            Get
                Return CType(Me("Drive6DelFolder"),String)
            End Get
            Set
                Me("Drive6DelFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive7DelFolder() As String
            Get
                Return CType(Me("Drive7DelFolder"),String)
            End Get
            Set
                Me("Drive7DelFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive8DelFolder() As String
            Get
                Return CType(Me("Drive8DelFolder"),String)
            End Get
            Set
                Me("Drive8DelFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive9DelFolder() As String
            Get
                Return CType(Me("Drive9DelFolder"),String)
            End Get
            Set
                Me("Drive9DelFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive10DelFolder() As String
            Get
                Return CType(Me("Drive10DelFolder"),String)
            End Get
            Set
                Me("Drive10DelFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive6NickName() As String
            Get
                Return CType(Me("Drive6NickName"),String)
            End Get
            Set
                Me("Drive6NickName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive7NickName() As String
            Get
                Return CType(Me("Drive7NickName"),String)
            End Get
            Set
                Me("Drive7NickName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive8NickName() As String
            Get
                Return CType(Me("Drive8NickName"),String)
            End Get
            Set
                Me("Drive8NickName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive9NickName() As String
            Get
                Return CType(Me("Drive9NickName"),String)
            End Get
            Set
                Me("Drive9NickName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Drive10NickName() As String
            Get
                Return CType(Me("Drive10NickName"),String)
            End Get
            Set
                Me("Drive10NickName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReservedSpace6() As Decimal
            Get
                Return CType(Me("ReservedSpace6"),Decimal)
            End Get
            Set
                Me("ReservedSpace6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReservedSpace7() As Decimal
            Get
                Return CType(Me("ReservedSpace7"),Decimal)
            End Get
            Set
                Me("ReservedSpace7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReservedSpace8() As Decimal
            Get
                Return CType(Me("ReservedSpace8"),Decimal)
            End Get
            Set
                Me("ReservedSpace8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReservedSpace9() As Decimal
            Get
                Return CType(Me("ReservedSpace9"),Decimal)
            End Get
            Set
                Me("ReservedSpace9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReservedSpace10() As Decimal
            Get
                Return CType(Me("ReservedSpace10"),Decimal)
            End Get
            Set
                Me("ReservedSpace10") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Windows_Plot_Mover.My.MySettings
            Get
                Return Global.Windows_Plot_Mover.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
